MirrorNight_Blog/MirrorNight_Blog/urls.py
import xadmin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('xadmin/op/MirrorNight/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MirrorNight_Blog/apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('about/', views.About.as_view(), name='about'),
    path('welcome/', views.Welcome.as_view(), name='welcome'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('categories/', views.CategoryList.as_view(), name='categories'),
    path('archives/', views.ArchiveList.as_view(), name='archives'),
    path('<str:type>_id=<int:id>/articles/', views.ArticleList.as_view(), name='articles'),
    path('photoalbums/', views.PhotoAlbumList.as_view(), name='photoalbums'),
    path('photoalbum_id=<int:id>/photos/', views.Photos.as_view(), name='photos'),
    path('article_id=<int:id>/comments/', views.Comment.as_view(), name='comments'),
    path('delete/comment_id=<int:id>', views.DeleteComment.as_view(), name='deletecomment'),
    path('article/<int:id>/', views.Detail.as_view(), name='detail'),
    path('index/', views.Index.as_view(), name='index'),
    path('mobilemsg/', views.MobileMsg.as_view(), name='mobilemsg'),
]

MirrorNight_Blog/apps/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('emailverificate/user_id=<int:user_id>/ctype=<int:ctype>/<int:year>/<int:month>/<int:day>/<int:hour>/<int:minute>/<int:second>/<str:code>/', views.EmailVerificate.as_view(), name='emailverificate'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('forget/', views.Forget.as_view(), name='forget'),
    path('myself/', views.Myself.as_view(), name='myself'),
]

MirrorNight_Blog/extra_apps/xadmin/views/detail.py
from __future__ import absolute_import
import copy

from crispy_forms.utils import TEMPLATE_PACK
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db import models
from django.forms.models import modelform_factory
from django.http import Http404
from django.template import loader
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.encoding import force_text, smart_text
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.html import conditional_escape
from xadmin.layout import FormHelper, Layout, Fieldset, Container, Column, Field, Col, TabHolder
from xadmin.util import unquote, lookup_field, display_for_field, boolean_icon, label_for_field

from .base import ModelAdminView, filter_hook, csrf_protect_m

# Text to display within change-list table cells if the value is blank.
EMPTY_CHANGELIST_VALUE = _('Null')


class ShowField(Field):
    template = "xadmin/layout/field_value.html"

    def __init__(self, callback, *args, **kwargs):
        super(ShowField, self).__init__(*args, **kwargs)
        self.results = [(field, callback(field)) for field in self.fields]

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK, extra_context=None, **kwargs):
        super(ShowField, self).render(form, form_style, context, template_pack, extra_context, **kwargs)
        if extra_context is None:
            extra_context = {}
        if hasattr(self, 'wrapper_class'):
            extra_context['wrapper_class'] = self.wrapper_class

        if self.attrs:
            if 'detail-class' in self.attrs:
                extra_context['input_class'] = self.attrs['detail-class']
            elif 'class' in self.attrs:
                extra_context['input_class'] = self.attrs['class']

        html = ''
        for field, result in self.results:
            extra_context['result'] = result
            if field in form.fields:
                if form.fields[field].widget != forms.HiddenInput:
                    extra_context['field'] = form[field]
                    html += loader.render_to_string(self.template, extra_context)
            else:
                extra_context['field'] = field
                html += loader.render_to_string(self.template, extra_context)
        return html


class ResultField(object):

    def __init__(self, obj, field_name, admin_view=None):
        self.text = '&nbsp;'
        self.wraps = []
        self.allow_tags = False
        self.obj = obj
        self.admin_view = admin_view
        self.field_name = field_name
        self.field = None
        self.attr = None
        self.label = None
        self.value = None

        self.init()

    def init(self):
        self.label = label_for_field(self.field_name, self.obj.__class__,
                                     model_admin=self.admin_view,
                                     return_attr=False
                                     )
        try:
            f, attr, value = lookup_field(
                self.field_name, self.obj, self.admin_view)
        except (AttributeError, ObjectDoesNotExist):
            self.text
        else:
            if f is None:
                self.allow_tags = getattr(attr, 'allow_tags', False)
                boolean = getattr(attr, 'boolean', False)
                if boolean:
                    self.allow_tags = True
                    self.text = boolean_icon(value)
                else:
                    self.text = smart_text(value)
            else:
                if isinstance(f.remote_field, models.ManyToOneRel):
                    self.text = getattr(self.obj, f.name)
                else:
                    self.text = display_for_field(value, f)
            self.field = f
            self.attr = attr
            self.value = value

    @property
    def val(self):
        text = mark_safe(
            self.text) if self.allow_tags else conditional_escape(self.text)
        if force_text(text) == '' or text == 'None' or text == EMPTY_CHANGELIST_VALUE:
            text = mark_safe(
                '<span class="text-muted">%s</span>' % EMPTY_CHANGELIST_VALUE)
        for wrap in self.wraps:
            text = mark_safe(wrap % text)
        return text


def replace_field_to_value(layout, cb):
    cls_str = str if six.PY3 else basestring
    for i, lo in enumerate(layout.fields):
        if isinstance(lo, Field) or issubclass(lo.__class__, Field):
            layout.fields[i] = ShowField(
                cb, *lo.fields, attrs=lo.attrs, wrapper_class=lo.wrapper_class)
        elif isinstance(lo, cls_str):
            layout.fields[i] = ShowField(cb, lo)
        elif hasattr(lo, 'get_field_names'):
            replace_field_to_value(lo, cb)


class DetailAdminView(ModelAdminView):

    form = forms.ModelForm
    detail_layout = None
    detail_show_all = True
    detail_template = None
    form_layout = None

    def init_request(self, object_id, *args, **kwargs):
        self.obj = self.get_object(unquote(object_id))

        if not self.has_view_permission(self.obj):
            raise PermissionDenied

        if self.obj is None:
            raise Http404(
                _('%(name)s object with primary key %(key)r does not exist.') %
                {'name': force_text(self.opts.verbose_name), 'key': escape(object_id)})
        self.org_obj = self.obj

    @filter_hook
    def get_form_layout(self):
        layout = copy.deepcopy(self.detail_layout or self.form_layout)

        if layout is None:
            layout = Layout(Container(Col('full',
                                          Fieldset(
                                              "", *self.form_obj.fields.keys(),
                                              css_class="unsort no_title"), horizontal=True, span=12)
                                      ))
        elif type(layout) in (list, tuple) and len(layout) > 0:
            if isinstance(layout[0], Column):
                fs = layout
            elif isinstance(layout[0], (Fieldset, TabHolder)):
                fs = (Col('full', *layout, horizontal=True, span=12),)
            else:
                fs = (
                    Col('full', Fieldset("", *layout, css_class="unsort no_title"), horizontal=True, span=12),)

            layout = Layout(Container(*fs))

            if self.detail_show_all:
                rendered_fields = [i[1] for i in layout.get_field_names()]
                container = layout[0].fields
                other_fieldset = Fieldset(_(u'Other Fields'), *[
                                          f for f in self.form_obj.fields.keys() if f not in rendered_fields])

                if len(other_fieldset.fields):
                    if len(container) and isinstance(container[0], Column):
                        container[0].fields.append(other_fieldset)
                    else:
                        container.append(other_fieldset)

        return layout

    @filter_hook
    def get_model_form(self, **kwargs):
        """
        Returns a Form class for use in the admin add view. This is used by
        add_view and change_view.
        """
        if self.exclude is None:
            exclude = []
        else:
            exclude = list(self.exclude)
        if self.exclude is None and hasattr(self.form, '_meta') and self.form._meta.exclude:
            # Take the custom ModelForm's Meta.exclude into account only if the
            # ModelAdmin doesn't define its own.
            exclude.extend(self.form._meta.exclude)
        # if exclude is an empty list we pass None to be consistant with the
        # default on modelform_factory
        exclude = exclude or None
        defaults = {
            "form": self.form,
            "fields": self.fields and list(self.fields) or '__all__',
            "exclude": exclude,
        }
        defaults.update(kwargs)
        return modelform_factory(self.model, **defaults)

    @filter_hook
    def get_form_helper(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.include_media = False
        layout = self.get_form_layout()
        replace_field_to_value(layout, self.get_field_result)
        helper.add_layout(layout)
        cls_str = str if six.PY3 else basestring
        helper.filter(cls_str, max_level=20).wrap(ShowField, admin_view=self)
        return helper

    @csrf_protect_m
    @filter_hook
    def get(self, request, *args, **kwargs):
        form = self.get_model_form()
        self.form_obj = form(instance=self.obj)
        helper = self.get_form_helper()
        if helper:
            self.form_obj.helper = helper

        return self.get_response()

    @filter_hook
    def get_context(self):
        new_context = {
            'title': _('%s Detail') % force_text(self.opts.verbose_name),
            'form': self.form_obj,

            'object': self.obj,

            'has_change_permission': self.has_change_permission(self.obj),
            'has_delete_permission': self.has_delete_permission(self.obj),

            'content_type_id': ContentType.objects.get_for_model(self.model).id,
        }

        context = super(DetailAdminView, self).get_context()
        context.update(new_context)
        return context

    @filter_hook
    def get_breadcrumb(self):
        bcs = super(DetailAdminView, self).get_breadcrumb()
        item = {'title': force_text(self.obj)}
        if self.has_view_permission():
            item['url'] = self.model_admin_url('detail', self.obj.pk)
        bcs.append(item)
        return bcs

    @filter_hook
    def get_media(self):
        return super(DetailAdminView, self).get_media() + self.form_obj.media + \
            self.vendor('xadmin.page.form.js', 'xadmin.form.css')

    @filter_hook
    def get_field_result(self, field_name):

MirrorNight_Blog/templates/blog-list.html
<!DOCTYPE html>
{% load static %}
<html class="ace-sidebar-on">
 <head>
  <meta charset="utf-8" />
  {% if type == 0 %}
      <title>Article List</title>
  {% elif type == 1 %}
      <title>Category List</title>
  {% else %}
      <title>Archive List</title>
  {% endif %}
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/web_logo.ico' %}" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
  <link href="{% static 'css/styleaaa.css' %}" rel="stylesheet" />
  <link href="{% static 'css/stylebb.css' %}" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/stylepp.css' %}" />
  <script type="text/javascript" src="{% static 'js/modernizr-3.3.1.min.js' %}"></script>
  <script>
      function MobileMsg()
      {
          var userAgentInfo = navigator.userAgent;
          var Agents = ["Android", "iPhone", "SymbianOS", "Windows Phone", "iPad", "iPod"];
          for (var v = 0; v < Agents.length; v++)
          {
              if (userAgentInfo.indexOf(Agents[v]) > 0)
              {
                  window.location.href="{% url 'blog:mobilemsg' %}";
                  break;
              }
          }
      }
      MobileMsg()
  </script>
  <style>
        * {
            box-sizing: border-box;
        }

        form {
            position: relative;
            width: 400px;
            top: 173px;
            margin-left: auto;
            margin-right: auto;
        }

        input, button {
            border: none;
            outline: none;
        }

        input {
            width: 100%;
            height: 42px;
            padding-left: 13px;
        }

        button {
            height: 42px;
            width: 42px;
            cursor: pointer;
            position: absolute;
        }

        .bar1 input {
            border: 2px solid #7BA7AB;
            border-radius: 5px;
            background: #F9F0DA;
            color: #9E9C9C;
        }
        .bar1 button {
            top: 0;
            right: 0;
            background: #7BA7AB;
            border-radius: 0 5px 5px 0;
        }
        .bar1 button:before {
            content: "\f002";
            font-family: FontAwesome;
            font-size: 16px;
            color: #F9F0DA;
        }
        .ea{
        position: relative;
        top: 47px;
        left: 350px;
        font-size: 20px;
        font-weight: bold;
        color: red;
    }
    .diandian{
        font-size: 35px;
        font-weight: bold;
        color: white;
    }
    .achai{
        position: relative;
        top: -60px;
    }
    </style>
 </head>
 <body id="top">
  <div class="ace-wrapper">
   <header id="ace-header" class="ace-container-shift ace-logo-in ace-head-boxed ace-nav-right">
    <div class="ace-head-inner">
     <div class="ace-head-container ace-container">
      <div class="ace-head-row">
       <div id="ace-head-col3" class="ace-head-col text-right">
        <button id="ace-sidebar-btn" class="btn btn-icon btn-light btn-shade"> <span class="ace-icon ace-icon-side-bar-icon"></span> </button>
       </div>
      </div>
     </div>
    </div>
   </header>
  </div>
  <div id="ace-sidebar">
   <button id="ace-sidebar-close" class="btn btn-icon btn-light btn-shade"> <span class="ace-icon ace-icon-close"></span> </button>
   <div id="ace-sidebar-inner">
    <article class="ace-card bg-primary">
     <div class="ace-card-inner text-center">
      {% if request.user.is_authenticated %}
          <img class="avatar avatar-195" src="{{ MEDIA_URL }}{{ request.user.head_portrait }}" width="195" height="195" alt="" />
          <h1>{{ request.user.username }}</h1>
      {% else %}
          <img class="avatar avatar-195" src="{% static 'img/logout.jpg' %}" width="195" height="195" alt="" />
          <h1>请登录</h1>
      {% endif %}
     </div>
    </article>
    <section class="widget widget_categories">
     <ul>
      {% if request.user.is_authenticated %}
          <li><a href="{% url 'user:myself' %}">个人</a></li>
      {% endif %}
      <li><a href="{% url 'blog:index' %}">主页</a></li>
      <li><a href="{% url 'blog:categories' %}">分类</a></li>
      <li><a href="{% url 'blog:archives' %}">归档</a></li>
      <li><a href="{% url 'blog:photoalbums' %}">相册</a></li>
      <li><a href="{% url 'blog:about' %}">关于</a></li>
      <li><a href="{% url 'blog:contact' %}">联系</a></li>
      {% if request.user.is_authenticated %}
          <li><a href="{% url 'user:logout' %}">注销</a></li>
      {% else %}
          <li><a href="{% url 'user:login' %}">登录</a></li>
      {% endif %}
      <li><a href="{% url 'user:register' %}">注册</a></li>
     </ul>
    </section>
   </div>
  </div>
  {% if type == 0 or type == 1 %}
      <div id="container">
          <div class="search bar1">
              {% ifequal type 0%}
                  <form method="post" action="{% url 'blog:articles' tt id %}" novalidate autocomplete="off">
              {% endifequal %}
              {% ifequal type 1%}
                  <form method="post" action="{% url 'blog:categories' %}" novalidate autocomplete="off">
              {% endifequal %}
                  {{ searchform.key_words }}
                  <button type="submit"></button>
                  {% csrf_token %}
              </form>
          </div>
      </div>
  {% endif %}
  <header id="header">
   <div class="logo">
    <a href="#">{{ title }}</a>
   </div>
  </header>
  <section id="main">
   <div class="inner">
    <section id="two" class="wrapper style2">
     <header>
      {% for thing in things.object_list %}
          {% ifequal type 0 %}
              <a href="{% url 'blog:detail' thing.id %}">{{ thing.title }}</a>
          {% endifequal %}
          {% ifequal type 1 %}
              <a href="{% url 'blog:articles' 'category' thing.id %}">{{ thing.title }}[{{ thing.num }}篇]</a>
          {% endifequal %}
          {% ifequal type 2 %}
              <a href="{% url 'blog:articles' 'archive' thing.id %}">{{ thing.title }}[{{ thing.num }}篇]</a>
          {% endifequal %}
          <br />
          <br />
      {% empty %}
          <a href="#">{{ msg }}</a>
          <div class="achai" align="center"><img src="{% static 'img/achai3.gif' %}" width="400" height="400"></div>
      {% endfor %}
     </header>
    </section>
   </div>
  </section>
  <div class="pageturn">
   <ul class="pagelist">
    {% if things.has_previous %}
        <li class="long"><a href="?{{ things.previous_page_number.querystring }}">上一页</a></li>
    {% endif %}

    {% for skip_page_id in things.pages %}
        {% if skip_page_id %}
            {% ifequal skip_page_id things.number %}
                <li class="active"><a href="#" class="page">{{ skip_page_id }}</a></li>
            {% else %}
                <li><a href="?{{ skip_page_id.querystring }}" class="page">{{ skip_page_id }}</a></li>
            {% endifequal %}
        {% else %}
            <li class="diandian">···</li>
        {% endif %}
    {% endfor %}

    {% if things.has_next %}
        <li class="long"><a href="?{{ things.next_page_number.querystring }}">下一页</a></li>
    {% endif %}
   </ul>
  </div>
  <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/options.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
 </body>
</html>

MirrorNight_Blog/templates/comment.html
<!DOCTYPE html>
{% load static %}
<html class="ace-sidebar-on">
 <head>
  <meta charset="utf-8" />
  <title>Comment</title>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/web_logo.ico' %}" />
  <link href="{% static 'css/bootstrap.min-zz.css' %}" rel="stylesheet" type="text/css" media="all" />
  <link href="{% static 'css/style-zz.css' %}" rel="stylesheet" type="text/css" media="all" />
  <link href="{% static 'css/styleaa.css' %}" rel="stylesheet" />
  <link href="{% static 'css/stylebb.css' %}" rel="stylesheet" />
  <script type="text/javascript" src="{% static 'js/modernizr-3.3.1.min.js' %}"></script>
  <script>
      function MobileMsg()
      {
          var userAgentInfo = navigator.userAgent;
          var Agents = ["Android", "iPhone", "SymbianOS", "Windows Phone", "iPad", "iPod"];
          for (var v = 0; v < Agents.length; v++)
          {
              if (userAgentInfo.indexOf(Agents[v]) > 0)
              {
                  window.location.href="{% url 'blog:mobilemsg' %}";
                  break;
              }
          }
      }
      MobileMsg()
  </script>
  <style>
      .ea{
          font-size: 20px;
          font-weight: bold;
          color: red;
      }
      h4.sofa{
          color: white;
          font-weight: bold;
          font-size: 30px;
          text-align: center;
      }
      .ckstyle img{
          max-width: 1150px;
          height: auto;
      }
      .ckstyle{
          color: white;
      }
      .test a{
          text-decoration: none;
          color: white;
      }
  </style>
 </head>
 <body id="top">
  <div class="ace-wrapper">
   <header id="ace-header" class="ace-container-shift ace-logo-in ace-head-boxed ace-nav-right">
    <div class="ace-head-inner">
     <div class="ace-head-container ace-container">
      <div class="ace-head-row">
       <div id="ace-head-col3" class="ace-head-col text-right">
        <button id="ace-sidebar-btn" class="btn btn-icon btn-light btn-shade"> <span class="ace-icon ace-icon-side-bar-icon"></span> </button>
       </div>
      </div>
     </div>
    </div>
   </header>
  </div>
  <div id="ace-sidebar">
   <button id="ace-sidebar-close" class="btn btn-icon btn-light btn-shade"> <span class="ace-icon ace-icon-close"></span> </button>
   <div id="ace-sidebar-inner">
    <article class="ace-card bg-primary">
     <div class="ace-card-inner text-center">
      {% if request.user.is_authenticated %}
          <img class="avatar avatar-195" src="{{ MEDIA_URL }}{{ request.user.head_portrait }}" width="195" height="195" alt="" />
          <h1>{{ request.user.username }}</h1>
      {% else %}
          <img class="avatar avatar-195" src="{% static 'img/logout.jpg' %}" width="195" height="195" alt="" />
          <h1>请登录</h1>
      {% endif %}
     </div>
    </article>
    <section class="widget widget_categories">
     <ul>
      {% if request.user.is_authenticated %}
          <li><a href="{% url 'user:myself' %}">个人</a></li>
      {% endif %}
      <li><a href="{% url 'blog:index' %}">主页</a></li>
      <li><a href="{% url 'blog:categories' %}">分类</a></li>
      <li><a href="{% url 'blog:archives' %}">归档</a></li>
      <li><a href="{% url 'blog:photoalbums' %}">相册</a></li>
      <li><a href="{% url 'blog:about' %}">关于</a></li>
      <li><a href="{% url 'blog:contact' %}">联系</a></li>
      {% if request.user.is_authenticated %}
          <li><a href="{% url 'user:logout' %}">注销</a></li>
      {% else %}
          <li><a href="{% url 'user:login' %}">登录</a></li>
      {% endif %}
      <li><a href="{% url 'user:register' %}">注册</a></li>
     </ul>
    </section>
   </div>
  </div>
  <section class="our-testimonials" id="testimonials">
   <a href="{% url 'blog:detail' id %}" class="text-center">《{{ title }}》</a>
   <h3 class="text-center">评论区</h3>
   <p class="text-center">共{{ num }}条评论</p>
   <div class="container">
    <div class="row">
     {% for comment in comments %}
         <div class="test">
             <img src="{{ MEDIA_URL }}{{ comment.author.head_portrait }}" class="img-responsive slideanim" alt="" />
             <h4 class="text-center slideanim">{{ comment.author.username }}</h4>
             <h4 class="text-center slideanim">
                 {{ comment.add_time }}
                 {% if request.user.is_authenticated %}
                     {% if request.user == comment.author or request.user.username == 'MirrorNight'%}
                         &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                         <a href="{% url 'blog:deletecomment' comment.id %}">删除评论</a>
                     {% endif %}
                 {% endif %}
             </h4>
             <div class="ckstyle">{{ comment.content|safe }}</div>
         </div>
     {% empty %}
         <div class="test">
            <h4 class="sofa">沙发空缺中，还不快抢~~</h4>
            <div align="center"><img src="{% static 'img/achai1.gif' %}" width="400" height="400"></div>
         </div>
     {% endfor %}
    </div>
   </div>
  </section>
  <section class="our-contacts slideanim" id="contact">
   <h3 class="text-center slideanim">发表评论</h3>
   <p class="text-center slideanim">兼听则明，偏信则暗</p>
   <div class="container">
    <div class="row">
     <div class="col-lg-12">
      <form role="form" method="post" action="{% url 'blog:comments' id %}" novalidate autocomplete="off">
       <div class="row">
        <div class="clearfix"></div>
        <div class="form-group col-lg-12 slideanim">
         {{ commentform.media }}
         {% if commentform.errors.content %}
            <ul class="ea">
                {% for error in commentform.errors.content %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
            </ul>
         {% endif %}
         {{ commentform.content }}
        </div>
        <div class="form-group col-lg-12 slideanim">
         {% if request.user.is_authenticated %}
             <button type="submit" class="btn-outline1">提交</button>
         {% else %}
             <button type="button" class="btn-outline1">请先登录</button>
         {% endif %}
        </div>
       </div>
       {% csrf_token %}
      </form>
     </div>
    </div>
   </div>
  </section>
  <section class="footer">
   <div class="copyright">
    <p>Copyright &copy; 2019.MirrorNight All rights reserved.</p>
    <br />
    <a href="http://www.miitbeian.gov.cn/publish/query/indexFirst.action">皖ICP备18025934号</a>
   </div>
  </section>
  <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/options.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  <script>
      CKEDITOR.replace('id_content', {disallowedContent:'img{width,height};img[width,height]', filebrowserImageUploadUrl:'/ckeditor/upload/', height:350, width:1135});
  </script>
 </body>
</html>

MirrorNight_Blog/templates/information.html
<!DOCTYPE html>
{% load static %}
<html>
 <head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>{{ title }}</title>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/web_logo.ico' %}" />
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  <link href="http://fonts.googleapis.com/css?family=Nova+Flat" rel="stylesheet" type="text/css" />
  <script>
      function MobileMsg()
      {
          var userAgentInfo = navigator.userAgent;
          var Agents = ["Android", "iPhone", "SymbianOS", "Windows Phone", "iPad", "iPod"];
          for (var v = 0; v < Agents.length; v++)
          {
              if (userAgentInfo.indexOf(Agents[v]) > 0)
              {
                  window.location.href="{% url 'blog:mobilemsg' %}";
                  break;
              }
          }
      }
      MobileMsg()
  </script>
 </head>
 <body>
  <div class="container">
   <div class="row pad-top text-center">
    <div class="col-md-6 col-md-offset-3 text-center">
     <h2>{{ information }}</h2>
    </div>
   </div>
   <div align="center"><img src="{% static 'img/achai4.gif' %}" width="400" height="400"></div>
   <div class="row text-center">
    <br> <br>
    <div class="col-md-8 col-md-offset-2">
     {% if type == 1 %}
         <a href="{% url 'blog:index' %}" class="btn btn-primary">返回</a>
     {% elif type == 2%}
         <a href="{% url 'user:login' %}" class="btn btn-primary">返回</a>
     {% else %}
         <a href="{% url 'blog:comments' id %}" class="btn btn-primary">返回</a>
     {% endif %}
    </div>
   </div>
  </div>
 </body>
</html>